package com.scaler.productservicenamanbhallafeb24.repositories;

import com.scaler.productservicenamanbhallafeb24.models.Product;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;
import java.util.Optional;

/*
it is an interface because if in future if we want to move to mongoDB
which framework our application will be using to talk to Database(mysql) ??
JPA
JpaRepository<Product, Long>
first argument here is the Product, it means that this particular class(ProductRepository)
will help to work with Entity: Product
or in other words, in ProductRepository i would want to work with which Model?

2nd argument : datatype of primary key of Entity/model class with which we are working
in this ProductRepository class
 */
public interface ProductRepository extends JpaRepository<Product, Long> {

    @Override
    Product save(Product p);
    //difference between p(input product param) and Product(return product) is the attributes that are automatically generated by database
    //which are not in p but will be there in Product(return product object)


    /*
    what is the difference between product passed as param and Product returned as a Product
    ANS: as param --decided by client
    json format
    {
    title: Uniqlo sports bag
    description: spacious and easy to carry
    image : https://www.img/image
    category : mens sports bag (type string)
    price : 999.123
    }

    return Product format is as per the
    Product entity json format

    {
    id
    title
    image
    description
    price
    category : (type Category)
    {
    id:
    name :
    }
     */

    //List<Product>findAll();
    //this is already present in crud repository to get list of all products, so no need to mention here
    //if u still mention use @Override

    //Optional<Product> findById(Long id);

    //findById, findByIdIs, findByIdequals--- all are same

    List<Product> findAllByTitle(String title);
    List<Product> findAllByCategory_titleIgnoreCase(String categoryName);

}
