#application.properties is the configuration of my application
#spring.application.name=productservicenamanbhallafeb24
#spring.jpa.hibernate.ddl-auto=validate
#ddl auto update means that when u are making any change in schema
#update the schema without doing anything, but when u are maintaining the version history
#should u update the schema directly or should u validate first?
#that's why change from update to validate
#spring.jpa.show-sql=true
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/productservice13feb26
#what is this datasource url?
#this is database URL, it can be on production or localhost etc.
#so 1 pre-requisite is to have Mysql DB installed on your local machine/publicly accessible server so that
#give its url here and see springboot in action

#spring.datasource.username=productservice13feb24user
#spring.datasource.password=secret
#since i have not provided password to the user in my database
# so i hv commented it out
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
#spring.flyway.baseline-on-migrate=true

#application.properties is the configuration of my application
spring.application.name=productservicenamanbhallafeb24
spring.jpa.hibernate.ddl-auto=validate
#ddl auto update means that when u are making any change in schema
#update the schema without doing anything, but when u are maintaining the version history
#should u update the schema directly or should u validate first?
#that's why change from update to validate
spring.jpa.show-sql=true
spring.datasource.url=${DB_URL}
#jdbc:mysql://productservicefeb24dbinstance.cx2uywqwwu2b.eu-north-1.rds.amazonaws.com:3306/productservice13feb26
#what is this datasource url?
#this is database URL, it can be on production or localhost etc.
#so 1 pre-requisite is to have Mysql DB installed on your local machine/publicly accessible server so that
#give its url here and see springboot in action

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
#since i have not provided password to the user in my database
#so i hv commented it out
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#spring.data.redis.url=http://redis.amazonaws.com/productserviceredis
#if redis is runnig on your local machine then no need to give url
#but if redis is running on AWS them url has to be given similar to RDS as database above
