package com.scaler.productservicenamanbhallafeb24.models;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;

/*
common attributes of models/entities
like id,createdAt,lastUpdatedAt,boolean is_deleted false;

so recommened practice is to have a BaseModel class as below and make every other model class inherit from BaseModel class
eg. Product class extends BaseModel class
and every other model class will hv their own attributes (in addition to those inherited from BaseModel Class)


concept of soft delete--Tombstone method, set the value of column (is_deleted) to true
donot hard delete(actually deleting the record/rows from the database)

most DB are faster with updating the rows than with deleting the rows
e.g. in case of MySql rows stored just like one after the other, so deleting any row would means to shift rows right of it
towards left,so this process is slow as compared to updating a column of the row/s
 */
@Getter
@Setter
@MappedSuperclass
/*
Hibernate/ORM/JPA doesnt automatically scan parent classes unles you explicitly tell it
"this parent class is a part of JPA Mapping Model"
Meaning of MappedSuperclass
“This class itself is not a table, but its fields should be mapped into child entity tables.”
 */
public class BaseModel implements Serializable {
//Note : even the Private attributes are present in the Child Classes
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /*
    in order to tell SPRING that this id will be generated by database
    i have to use @Generatedvalue
    else, spring will assume that id will also be created by us
     */
    private Long id;

    private Date createdAt;
    private Date updatedAt;
    private Boolean is_deleted;

//    public Date getCreatedAt() {
//        return createdAt;
//    }

}

/*
Quesn : if u have a object of Child Class say (Product) and we have a method in BaseModel class as above
i.e.
public Date getCreatedAt() {
        return createdAt;
    }
will the child class be able to access this method?
i.e. Product p = new Product();
can we write p.getCreatedAt()

Answer : YES as child will inherit all the attributes and methods of Parent class

NExt thing :
how to connect my application to the Database
go to start.spring.io
1. I need to import Myssql driver and Spring Data JPA
add dependencies, click on explore
copy and paste in pom.xml

after this we tried to run the application
there was no compile time error, bt there was Runtime error, application was not able to run, why??
we recently added/imported spring DATA jpa and mysql driver dependencies

bt Have we told spring that "Hey spring, this is the URL of my DB, password of my DB, username of my DB,port of my DB
etc.
NO, not yet
so we connect to Mysql


after to connecting to MySql DBMS,

HERE WE WILL START QUERIES in CONSOLE
quesn : for each service, would u want to share same DB acrros services or do u want a separate datasource for each services
so that each of the services remain isolated from each other/services donot inadverdently impact each other?
Answer : separate DB, whenevr u are creating microservice based environment
good practice is to have completely isolated DB as well

i.e.
imagine each service as a separate company having an isolated environment

Directly going to others service's DB is bad, instead follow a path
i.e via controller-->services-->repository-->DB

in console-- u will create a Database


for safety purpose, for each database, i will create a separate user as well in the database itself
as i donot want to share Mysql connection username and password in the application properties

so create a new user and grant all privileges to this user
like read,write,delete etc.

once this is done, i.e user and database  is created and permissionns are granted to user
go to application properties again
comment out password
and change the user name as per name set in console database
and in url change the database as set by you in console

application will now successfully start

further we will see how to add tables into database
which will be done with the help of ORM(object relational mapping) HIBERNATE
but hv i told spring boot application or ORM that this the class, info for which u should store in DB ??

NO
so first thing, we have annotate the model which we want to store in database with
@Entity


 */